counting/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('form.urls')),
]

form/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'form'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('form/', views.form_new, name="form_new"),
    path('form_detail/<int:pk>/', views.Details.as_view(), name='form_detail'),
    path('form/<int:pk>/edit/', views.form_edit, name='form_edit'),
    path('customer_list/', views.Customers_list.as_view(), name='customer_list'),
    path('room_detail/<int:number>/', views.Room_details.as_view(), name='room_detail'),
    path('room_list/', views.Room_list.as_view(), name='room_list'),
]

posts/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    ]

form/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
# Create your models here.

class Room(models.Model):
    room_number = models.IntegerField()

    def __str__(self):
        return (str)(self.room_number)

    def get_absolute_url(self):
        return reverse('room_detail', kwargs={'pk': self.pk})


class Customer(models.Model):
    name= models.CharField(max_length=200)
    number = models.CharField(max_length=10)
    address = models.TextField()
    email = models.EmailField(blank=True)
    dateofjoining = models.DateTimeField(default=datetime.now, blank=True)
    duration = models.IntegerField()
    fee = models.IntegerField()
    checkout= models.BooleanField(blank=True)
    room_number= models.ForeignKey(Room, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

posts/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Posts(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural = "Posts"

counting/views.py
from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello world")

form/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .form import CustomerForm
from .models import Customer,Room
from django.views.generic import ListView, DetailView, TemplateView
# Create your views here.

class Home(TemplateView):
    template_name = 'form/home.html'

def form_new(request):
    if request.method == "POST":
        form =CustomerForm(request.POST)
        if form.is_valid():
            customer=form.save(commit=False)
            customer.save()
            return redirect('form_detail', pk=customer.pk)
    else:
        form = CustomerForm()
    return render(request, 'form/form_new.html', {'form': form})


class Details(DetailView):
    model = Customer
    template_name = 'form/customer_detail.html'

def form_edit(request, pk):
    post = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        form = CustomerForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('form_detail', pk=post.pk)
    else:
        form = CustomerForm(instance=post)
    return render(request, 'form/form_new.html', {'form': form})

class Customers_list(ListView):
     template_name = 'form/customer_list.html'
     context_object_name = 'customer_list'
     def get_queryset(self):
         return Customer.objects.filter(checkout=False)

class Room_list(ListView):
    template_name = "form/room_list.html"
    context_object_name = "room_list"
    def get_queryset(self):
        return Room.objects.all()

class Room_details(DetailView):
    model = Room
    template_name = "form/room_detail.html"
    context_object_name = "customer"

    # def get_queryset(self):
    #     room_use = Room.objects.get(pk=self.kwargs['pk'])
    #     room_use = room_use.customer_set.all()
    #     print(room_use)
    #     return room_use

    def get_object(self, queryset=None):
        obj = get_object_or_404(self.model, room_number=self.kwargs['number'])
        print(obj)
        return obj

    def get_context_data(self, **kwargs):
        room = super().get_context_data()
        room['members'] = room['customer'].customer_set.all()
        print(room)
        return room
        # return room.customer_set.all()



def checkout(request):
    customer= Customer.objects.get(checkout=True)

posts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    context={
        'tilte':'Latest post',

    }

    return render(request,"posts/index.html", context)

form/templates/form/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Omkars</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

form/templates/form/customer_detail.html
{% extends "form/base.html" %}
{% block content %}
    <div>
        <li>{{ customer.name }}</li>
        <ul>{{ customer.number }}</ul>
        <ul>{{ customer.dateofjoining }}</ul>
        <ul>{{ customer.duration }}</ul>
        <ul>{{ customer.fee }}</ul>
    </div>


{% endblock %}

form/templates/form/customer_list.html
{% extends 'form/base.html' %}
{% block content %}

    <div>
        {% for room in customer_list %}
            <li><a href="{% url 'form:form_detail' room.id %}"> {{ room.name }}</a></li>
            <ul>{{ room.number }}</ul>
            <ul>{{ room.room_number }}</ul>
        {% endfor %}
    </div>

{% endblock %}

form/templates/form/form_new.html
{% extends "form/base.html" %}
{% block content %}
    <section class="registerform_section">
    <h1 class="col-md-3">New Registration</h1>
        <div class="container">

            <div class="row">

                <form class="form_center" method="post">
                    {% csrf_token %}
                    <label>Name:</label>
                    {{ form.name }}
                    <label>Phone no:</label>
                    {{ form.number }}
                    <label>Address:</label>
                    {{ form.address }}
                    <label>Emailid:</label>
                    {{ form.email }}
                    <label>DateofJoining:</label>
                    {{ form.dateofjoining }}
                    <label>Duration(Months):</label>
                    {{ form.duration }}
                    <label>Fee(discussed):</label>
                    {{ form.fee }}
                    <label>Room number:</label>
                    {{ form.room_number }}
                    <button type="submit">Register</button>
                </form>

            </div>

        </div>
    </section>
{% endblock %}

form/templates/form/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-7">
    <h1>Welcome</h1>
    <a href="{% url 'form:form_new' %}">Register</a>
    <a href="{% url 'form:customer_list' %}">Customers registered</a>
    <a href="{% url 'form:room_list' %}">Rooms present</a>
    <label></label>
        </div>
    </div>
</div>
</body>
</html>

form/templates/form/room_detail.html
{% extends 'form/base.html' %}
{% block content %}
    {{ customer.room_number }}
    {{ customer.members }}

    {% for i in members %}
        {{ i.name }}
    {% endfor %}

{% endblock %}

form/templates/form/room_list.html
{% extends 'form/base.html' %}
{% block content %}
    {% for user in room_list %}
        <li><a href="{% url 'form:room_detail' user.room_number %}">{{ user.room_number }}</a></li>
    {% endfor %}
{% endblock %}

posts/templates/posts/index.html
{% extends "posts/layout.html" %}

{% block content %}
<h1>posts </h1>
{% endblock %}

posts/templates/posts/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <header>
        <h1>Blog</h1>
    </header>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>